title: Stem Nexus
author: contact-us
# email: 
description: > # this means to ignore newlines until "baseurl:"
  Helping develop skills in Science, Technology, Engineering, and Math for people of all ages. 
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: stem-nexus # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
